'use strict';
const $=s=>document.querySelector(s);let plugins=[],category='',query='',order='source',toastTimer;
function element(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e}
function https(value){const u=new URL(value);if(u.protocol!=='https:')throw new Error('需要 HTTPS 链接');return u.href}
function moduleURL(p){return https(new URL(p.url).searchParams.get('plugin'))}
function importURL(p){return 'egern:/modules/new?name='+encodeURIComponent(p.name)+'&url='+encodeURIComponent(moduleURL(p))}
function cleanDesc(s){return s.replace(/\\+n/g,'\n')}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
async function copy(p,button){try{await navigator.clipboard.writeText(moduleURL(p));button.textContent='已复制';toast('已复制作者原始链接');setTimeout(()=>button.textContent='复制链接',1800)}catch{showDetail(p);toast('请在详情中长按链接文本复制')}}
function actions(p){const a=element('div','actions');const link=element('a','import','导入 Egern');link.href=importURL(p);link.setAttribute('aria-label','将'+p.name+'导入 Egern');link.onclick=()=>toast('请在 Egern 中确认并保存模块');const c=element('button','copy','复制链接');c.onclick=()=>copy(p,c);a.append(link,c);return a}
function filtered(){let list=plugins.filter(p=>(!category||p.tag.includes(category))&&(!query||[p.name,p.desc,...p.author.map(a=>a.name)].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase())));if(order==='recent')list.sort((a,b)=>b.date.localeCompare(a.date));if(order==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'zh-CN'));return list}
function render(){const list=filtered();$('#heading').textContent=category||'全部插件';$('#count').textContent=list.length+' 个结果 / 共 '+plugins.length+' 个';$('#cards').replaceChildren();$('#empty').hidden=list.length!==0;for(const p of list){const card=element('article','card'),top=element('div','card-top');const icon=element('img','icon');icon.src=https(p.icon);icon.alt='';icon.loading='lazy';icon.onerror=()=>icon.replaceWith(element('span','icon initial',p.name.slice(0,1)));const title=element('div');const t=element('button','card-title',p.name);t.onclick=()=>showDetail(p);title.append(t,element('div','author',p.author.map(a=>a.name).join(' / ')));top.append(icon,title);const meta=element('div','meta'),tags=element('div','tags');p.tag.forEach(t=>tags.append(element('span','tag'+(t==='依赖'?' dependency':''),t)));meta.append(tags,element('time','date',p.date.slice(0,10)));const a=actions(p),more=element('button','more','详情');more.onclick=()=>showDetail(p);a.append(more);card.append(top,element('p','desc',cleanDesc(p.desc)),meta,a);$('#cards').append(card)}document.querySelectorAll('nav button').forEach(b=>{const on=b.dataset.category===category;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))})}
function showDetail(p){const box=$('#detail-content');box.replaceChildren();box.append(element('h2','',p.name));const authors=element('p','author');p.author.forEach(a=>{const link=element(a.homepage?'a':'span','',a.name);if(a.homepage){link.href=https(a.homepage);link.target='_blank';link.rel='noopener'}authors.append(link)});box.append(authors,element('p','full-desc',cleanDesc(p.desc)),element('p','','目录更新时间：'+p.date),element('p','','Egern 兼容性：尚未逐项实测。MITM、脚本开关和依赖以插件原文为准。'));const label=element('label','','作者原始订阅地址');label.htmlFor='raw-url';const url=element('textarea','url');url.id='raw-url';url.readOnly=true;url.rows=3;url.value=moduleURL(p);url.onclick=()=>url.select();box.append(label,url,actions(p));const src=element('p'),link=element('a','','查看插件原文 ↗');link.href=moduleURL(p);link.target='_blank';link.rel='noopener';src.append(link);box.append(src);if(!$('#detail').open)$('#detail').showModal()}
$('#search').addEventListener('input',e=>{query=e.target.value.trim();render()});$('#sort').addEventListener('change',e=>{order=e.target.value;render()});$('#reset').onclick=()=>{category='';query='';$('#search').value='';render()};$('#help-open').onclick=()=>$('#help').showModal();document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('#search').focus()}});
fetch('catalog.json').then(r=>{if(!r.ok)throw new Error('目录无法读取');return r.json()}).then(data=>{if(!Array.isArray(data.lists))throw new Error('目录格式错误');plugins=data.lists;plugins.forEach(p=>{moduleURL(p);https(p.icon);p.author.forEach(a=>{if(a.homepage)https(a.homepage)})});$('#total').textContent=plugins.length;const counts=new Map;plugins.forEach(p=>p.tag.forEach(t=>counts.set(t,(counts.get(t)||0)+1)));for(const [t,n] of [['',plugins.length],...counts]){const b=element('button','',t||'全部插件');b.dataset.category=t;b.append(element('small','',n));b.onclick=()=>{category=t;render()};$('#categories').append(b)}data.notice.forEach(n=>$('#source-notices').append(element('p','',n)));render();registerTools()}).catch(()=>{$('#error').hidden=false;$('#count').textContent='加载失败'});
function registerTools(){if(!document.modelContext?.registerTool)return;const controller=new AbortController;window.addEventListener('pagehide',()=>controller.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'filter_plugins',description:'搜索插件并更新页面筛选，返回名称和作者原始链接；不会安装插件。',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.query!=='string'||Object.keys(input).some(k=>k!=='query'))throw new Error('query 必须为字符串');query=input.query.trim();category='';$('#search').value=input.query;render();return {count:filtered().length,plugins:filtered().slice(0,20).map(p=>({name:p.name,url:moduleURL(p)}))}}},{signal:controller.signal})).catch(()=>{})}catch{}}
